name: "Puter Subdomain Deploy"
description: "Deploy files from a repository path to Puter FS and bind/update a Puter subdomain."
author: "Puter"

inputs:
  subdomain:
    description: "Subdomain to deploy (e.g. my-site or my-site.puter.site)."
    required: true
  puter_path:
    description: "Destination directory path in Puter FS."
    required: true
  puter_token:
    description: "Puter auth token. Pass from GitHub secrets."
    required: true
  source_path:
    description: "Local path in the checked out repository to deploy."
    required: false
    default: "."
  include_hidden:
    description: "Whether to include hidden files/directories (dotfiles)."
    required: false
    default: "false"
  concurrency:
    description: "Number of concurrent uploads."
    required: false
    default: "8"

outputs:
  deployed_files:
    description: "Total files uploaded."
    value: ${{ steps.run.outputs.deployed_files }}
  deployment_url:
    description: "Resolved site URL."
    value: ${{ steps.run.outputs.deployment_url }}
  binding_action:
    description: "Subdomain binding result: created, updated, or unchanged."
    value: ${{ steps.run.outputs.binding_action }}

runs:
  using: "node24"
  main: "dist/index.cjs"
